name: MinecraftChallengePlugin
version: 1.0
main: com.dammnranaah.minecraftchallenge.MinecraftChallengePlugin
api-version: 1.20
commands:
  challenge:
    description: Manage Minecraft challenges
    usage: /challenge <start|stop|list>
    permission: challenge.use
